// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using MLNetSampleFCCML.Model;

namespace MLNetSampleFCCML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private static string DATA_FILEPATH = ModelBuilder.GetAbsolutePath(@"../../../../Dataset\LasVegasTripAdvisorReviews-Dataset.csv");

        static void Main(string[] args)
        {
            ModelBuilder.CreateModel();
            return;
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Score with predicted Score from sample data...\n\n");
            Console.WriteLine($"User country: {sampleData.User_country}");
            Console.WriteLine($"Nr. reviews: {sampleData.Nr__reviews}");
            Console.WriteLine($"Nr. hotel reviews: {sampleData.Nr__hotel_reviews}");
            Console.WriteLine($"Helpful votes: {sampleData.Helpful_votes}");
            Console.WriteLine($"Period of stay: {sampleData.Period_of_stay}");
            Console.WriteLine($"Traveler type: {sampleData.Traveler_type}");
            Console.WriteLine($"Pool: {sampleData.Pool}");
            Console.WriteLine($"Gym: {sampleData.Gym}");
            Console.WriteLine($"Tennis court: {sampleData.Tennis_court}");
            Console.WriteLine($"Spa: {sampleData.Spa}");
            Console.WriteLine($"Casino: {sampleData.Casino}");
            Console.WriteLine($"Free internet: {sampleData.Free_internet}");
            Console.WriteLine($"Hotel name: {sampleData.Hotel_name}");
            Console.WriteLine($"Hotel stars: {sampleData.Hotel_stars}");
            Console.WriteLine($"Nr. rooms: {sampleData.Nr__rooms}");
            Console.WriteLine($"User continent: {sampleData.User_continent}");
            Console.WriteLine($"Member years: {sampleData.Member_years}");
            Console.WriteLine($"Review month: {sampleData.Review_month}");
            Console.WriteLine($"Review weekday: {sampleData.Review_weekday}");
            Console.WriteLine($"\n\nActual Score: {sampleData.Score} \nPredicted Score: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ';',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
