// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;
using System;

namespace MLNetSampleFCCML.Model
{
    public class ModelInput
    {
        [ColumnName("User country"), LoadColumn(0)]
        public string User_country { get; set; }


        [ColumnName("Nr. reviews"), LoadColumn(1)]
        public float Nr__reviews { get; set; }


        [ColumnName("Nr. hotel reviews"), LoadColumn(2)]
        public float Nr__hotel_reviews { get; set; }


        [ColumnName("Helpful votes"), LoadColumn(3)]
        public float Helpful_votes { get; set; }


        [ColumnName("Score"), LoadColumn(4)]
        public float Score { get; set; }


        [ColumnName("Period of stay"), LoadColumn(5)]
        public string Period_of_stay { get; set; }


        [ColumnName("Traveler type"), LoadColumn(6)]
        public string Traveler_type { get; set; }


        [ColumnName("Pool"), LoadColumn(7)]
        public bool Pool { get; set; }


        [ColumnName("Gym"), LoadColumn(8)]
        public bool Gym { get; set; }


        [ColumnName("Tennis court"), LoadColumn(9)]
        public bool Tennis_court { get; set; }


        [ColumnName("Spa"), LoadColumn(10)]
        public bool Spa { get; set; }


        [ColumnName("Casino"), LoadColumn(11)]
        public bool Casino { get; set; }


        [ColumnName("Free internet"), LoadColumn(12)]
        public bool Free_internet { get; set; }


        [ColumnName("Hotel name"), LoadColumn(13)]
        public string Hotel_name { get; set; }


        [ColumnName("Hotel stars"), LoadColumn(14)]
        public string Hotel_stars { get; set; }


        [ColumnName("Nr. rooms"), LoadColumn(15)]
        public float Nr__rooms { get; set; }


        [ColumnName("User continent"), LoadColumn(16)]
        public string User_continent { get; set; }


        [ColumnName("Member years"), LoadColumn(17)]
        public float Member_years { get; set; }


        [ColumnName("Review month"), LoadColumn(18)]
        public string Review_month { get; set; }


        [ColumnName("Review weekday"), LoadColumn(19)]
        public string Review_weekday { get; set; }

        public void PrintToConsole()
        {
            Console.WriteLine($"--------------------------------------");
            Console.WriteLine($"User country: {this.User_country}");
            Console.WriteLine($"Nr. reviews: {this.Nr__reviews}");
            Console.WriteLine($"Nr. hotel reviews: {this.Nr__hotel_reviews}");
            Console.WriteLine($"Helpful votes: {this.Helpful_votes}");
            Console.WriteLine($"Period of stay: {this.Period_of_stay}");
            Console.WriteLine($"Traveler type: {this.Traveler_type}");
            Console.WriteLine($"Pool: {this.Pool}");
            Console.WriteLine($"Gym: {this.Gym}");
            Console.WriteLine($"Tennis court: {this.Tennis_court}");
            Console.WriteLine($"Spa: {this.Spa}");
            Console.WriteLine($"Casino: {this.Casino}");
            Console.WriteLine($"Free internet: {this.Free_internet}");
            Console.WriteLine($"Hotel name: {this.Hotel_name}");
            Console.WriteLine($"Hotel stars: {this.Hotel_stars}");
            Console.WriteLine($"Nr. rooms: {this.Nr__rooms}");
            Console.WriteLine($"User continent: {this.User_continent}");
            Console.WriteLine($"Member years: {this.Member_years}");
            Console.WriteLine($"Review month: {this.Review_month}");
            Console.WriteLine($"Review weekday: {this.Review_weekday}");
        }
    }
}
